// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  featured: dynamic(() => import("./Featured")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  text_chat: dynamic(() => import("./TextChat")),
  work: dynamic(() => import("./Work")),
};
